Repository gip-inclusion/pilotage, pull requests merged in 2025-03, with the labels that each got.

#109 github: Correction de `require-labels.yml` pour la merge queue
  .github/workflows/require-labels.yml
Labels: no-changelog

#111 Maj du theme en v2.7.6
  pilotage/static/vendor/theme-inclusion/javascripts/app.js
  pilotage/static/vendor/theme-inclusion/stylesheets/app.css
Labels: tech

#108 Configuration : Mise en place de Sentry
  config/settings/base.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: ajouté

#117 Configuration : Activer `GZipMiddleware` and `ConditionalGetMiddleware` pour améliorer le temps de réponse HTTP
  config/settings/base.py
Labels: ajouté

#107 Configuration : Logs JSON pour DataDog
  config/settings/base.py
  config/settings/dev.py
  pilotage/itoutils/__init__.py
  pilotage/itoutils/logging.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: modifié

#118 Pilotage : Ajout de l'API `/dataset`
  config/settings/base.py
  config/urls.py
  pilotage/api/__init__.py
  pilotage/api/urls.py
  pilotage/api/views.py
  pilotage/itoutils/departments.py
  pilotage/itoutils/metabase.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/api/__snapshots__/test_views.ambr
  tests/api/test_views.py
  tests/conftest.py
Labels: ajouté

#127 Configuration CORS pour l'API
  config/settings/base.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: ajouté

#128 API `/dataset` : Ajout du nom pour les structures data·inclusion
  pilotage/api/views.py
Labels: ajouté
